[package]
name = "pgxn_build"
version = "0.1.0"
edition = "2021"

[dependencies]
pgxn_meta = "0.4"
thiserror = "1.0"
ureq = { version = "*", features = ["json"] }
url = "2.5"

[dev-dependencies]
httpmock = "0.7"
serde_json = "1.0"
sha2 = "0.10"
tempfile = "3.12"
