[package]
name = "pgxn_build"
version = "0.1.0"
description = "Build PGXN distributions"
repository = "https://github.com/pgxn/build"
documentation = "https://docs.rs/pgxn_build/"
authors = ["David E. Wheeler <david@justatheory.com>"]
readme = "README.md"
keywords = ["pgxn", "postgres", "postgresql", "extension", "validation"]
license = "PostgreSQL"
categories = ["web-programming", "database"]
edition = "2021"
exclude = [ ".github", ".vscode", ".gitignore", ".ci", ".pre-*.yaml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
iri-string = "0.7"
log = { version = "0.4.22", features = ["kv"] }
pgxn_meta = "0.5.1"
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
ureq = { version = "*", features = ["json"] }
url = "2.5"
zip = "2.2"

[dev-dependencies]
httpmock = "0.7"
sha2 = "0.10"
tempfile = "3.14"
hex = "0.4"
